# Generated by Django 6.0.7 on 2026-08-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmember',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
