# Generated by Django 6.0.7 on 2026-08-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
    ]
